coverage:
  status:
    project:
      default:
        threshold: 0% 
        branches:
          - main
    patch:
      default:
        threshold: 0% 
        branches:
          - main

comment:
  layout: reach, diff, flags, files
  behavior: default
  require_changes: false
  branches:
    - main
    
ignore:
  - "LICENSES"
  - "Makefile"
  - ".gitignore"
  - "**/*.sh"
  - "**/*.pb.go"
  - "**/*_test.go"
  - ".git"
  - "*.yml"
  - "*.yaml"
  - "*.md"
  - "*.tpl"
  - "docs/.*"
  - "**/*.proto"
  - "e2e/testdata/.*"
  - "e2e/smkoe/.*"
  - "e2e/helper.go"
  - "tools/gogs/gen/testdata/.*"
  - "examples/.*"